### ISSUE TITLE
Fixes for enable_4bit_background()

### ISSUE THREAD

**Issue by iamgreaser** [thp/dos-game-jam-demo-disc#1]
Still chipping away at my DOS Games End Of Year Jam 2023 entry, and thought I'd have a nosey at this code...

Looking at `catalog/vgautil.h`, function `enable_4bit_background()`:

```c
        case DISPLAY_ADAPTER_EGA:
            {
                // TODO: Is this mirrored by the BIOS?
                uint8_t tmp = inp(0x03da);
                outp(0x03c0, 0x10);
                tmp = inp(0x03c1);
                tmp &= ~(1<<3);
                // FIXME: Masking the bit in tmp doesn't work,
                // so we just set it to zero (tested in DOSBox)
                outp(0x03c0, 0);
            }
```

The attribute controller is not readable on an EGA[1], and attempting to read it results in an open-bus result of 0xFF (a real IBM EGA has pull-ups on the data bus according to the schematic).

[1]: Well, OK, it *kinda* is... that is, if you read 0x3DA (or 0x3BA in monochrome cases), the attribute controller will contribute bits 0,3,4,5, while some discrete logic will provide bits 1,2 for light pen status stuff. But the registers you write into it cannot be read back.

From my tests in 86Box, the EGA BIOS does have the `AX=0x1003` call which behaves as expected, and on top of that, it updates `0040:0065` bit 5 as if it's a CGA. So you might as well get rid of that switch block and handle EGA the same way you handle VGA here.

On the contrary, the CGA does not have this call at least on the 1982 release of the IBM PC (I don't have a small enough DOS on hand for the 1981 release and its 64 KB of RAM), so what you're doing is correct aside from the fact that there's a typo where it says it's mirrored at "0040:0064" - this is actually the second byte of the location of the CRTC base I/O port address.
(If I recall correctly, the CGA does not have a video BIOS on the card itself, but relies on the system's BIOS to provide all the calls, hence why I needed to emulate one of the earliest machines.)

As for VGA:
```c
                regs.h.ah = 0x10;
                regs.h.al = 0x03;
                regs.h.bl = 0x00;
```
Ralf Brown's Interrupt List (RBIL) suggests also setting BH to 0 for this call "to avoid problems on some adapters".

Speaking of RBIL, if you don't have it already you'll definitely want it: https://www.cs.cmu.edu/~ralf/files.html

**Comment by thp** [comment]
Thanks for the input! Wonder if you want to turn this into a pull request?

**Comment by iamgreaser** [comment]
Can do. But before I do that, would you be able to give me a list of tools I need to build this thing? Not sure if you're using DJGPP or Watcom or Turbo C++ or whatever.

**Comment by thp** [comment]
You need OpenWatcom v2, you can download builds here if you don't want to build it yourself: https://github.com/open-watcom/open-watcom-v2/releases

Make sure `owcc` is in your `$PATH` (e.g. on 64-bit Linux, add `binl64`). You probably also want to set `$WATCOM` to the OpenWatcom root (e.g. the folder that contains `binl64`).

Other tools you need: `make`, `python3`, `mkisofs` (for actually creating an ISO image).

After that, just running `make` in the `catalog` folder should build the binaries + create an ISO (the game files are not part of the Git repository, but you can still launch the menu and do all the things with the exception of launching games until you put them into the right spot).

**Comment by iamgreaser** [comment]
OK, got `catalog` building with the 2024-01-01 build but I had to build `chain.s` using `wasm chain.s`... anyway, it seems to be working. I'll take a look at the video mode stuff in 86Box.

**Comment by thp** [comment]
> OK, got `catalog` building with the 2024-01-01 build but I had to build `chain.s` using `wasm chain.s`... anyway, it seems to be working. I'll take a look at the video mode stuff in 86Box.

Didn't that makefile rule take care of it?

```
chain.o: chain.s
	owcc -c -o $@ $^
```
