### ISSUE TITLE
Being able to switch between VGA, VESA and text mode from the same program

### ISSUE THREAD

**Issue by badsectoracula** [thp/dos-game-jam-demo-disc#10]
Instead of having separate programs for each menu, how about being able to toggle the graphics mode from the same program (perhaps also allowing both VESA and VGA)? Not only it should address readability but also make it easier to switch between the menus/modes from the bootable CD without having to exit the program.

**Comment by thp** [comment]
Implemented in 9dc0874ccc82b218f3dda9b25696adf30a4b354e using the F5 button (there are still separate programs, but they can be transparently switched, and there's only a single entry point `start.exe`.
