### ISSUE TITLE
add an install option

### ISSUE THREAD

**Issue by jtsiomb** [thp/dos-game-jam-demo-disc#4]
Some of the games don't run properly without being able to write files. The mechanism of hooking file I/O and redirecting write to a temp directory is awsome, but I think a simple option to just install the item explicitly makes much sense too. There could even be a batch file that is executed if present, to set things up after the copy operation.

**Comment by thp** [comment]
Implemented in 1a07ab4cb0b8035c0ca7a946d0ce9d97ea787415
