### ISSUE TITLE
Screenshot viewer for the text mode menu

### ISSUE THREAD

**Issue by jtsiomb** [thp/dos-game-jam-demo-disc#9]
I added experimental support for viewing screenshots from the text mode menu in the "nuclear" branch. Should this be merged?

disc image for easy testing: http://mutantstargoat.com/~nuclear/tmp/demodisc-nuclear1.iso

**Comment by thp** [comment]
Merged in 04f58fc86bda5d2e7c7844a3973cd28933ba24cb and integrated in 9437385910abd596c2c34c9c5f8e8e86e605e176
